### ISSUE TITLE
Añadir un curso de python orientado a análisis de datos

### ISSUE THREAD

**Issue by koldLight** [PyLadiesMadrid/recursos#5]
Hola!

He visto la referencia a este repo en el telegram de pyladies.

¿Os parecería bien o sería de utilidad añadir un nuevo recurso? Tengo este curso publicado: https://github.com/koldLight/curso-python-analisis-datos

Con estas características:

* En español
* Si se imparte de forma guiada (con profe) se hace en unas 20 - 25 horas. Cada uno por su cuenta, supongo que andará por ahí, menos si ya se sabe python, más si se empieza sin conocimientos del lenguaje.
* Orientado todo a datos (no hay backend ni nada de eso)
* Suelo impartirlo en masters de Big Data y formaciones a empresas y en general la gente sale contenta

Además, me gustaría darle un poco de difusión entre grupos de mujeres, porque me parece muy triste que tenga 30 y pico estrellas 100% de hombres jaja.

Entonces si os parece interesante... os puedo hacer una PR para añadirlo al README.md.

Muchas gracias

**Comment by aliciapj** [comment]
Hola @koldLight! 

Ante todo disculpa el restraso en responder! Le hemos echado un ojo a tu repo y nos parece genial, precisamente contenido como éste es el que nos gustaría tener en nuestro repo, así que te agradecemos muchísimo la aportación.

Si te parece, haznos una PR al repo y una vez esté publicado lo anunciamos también por el grupo de telegram para que llegue a más gente.

Y al hilo de ésto... te gustaría organizar alguna demo/workshop/charla en el grupo? Al estar basado en jupyter notebooks creemos que sería relativamente fácil presentar alguno de los notebooks y que así a lxs asistentes les pique el gusanillo y sigan investigando el resto... además llevamos tiempo queriendo hacer alguna sesión de visualización de datos y creo que tienes algún notebook relativo a eso... cómo lo ves?

Muchas gracias y feliz día :)

**Comment by koldLight** [comment]
PR hecha :)

Vale, gracias por ofrecérmelo! Me parece bien lo de organizar un workshop / charla. Cosas que se me ocurren que pueden ser interesantes:

* Una mini-intro de teoría: escalas de colores, de ejes, dónde poner el cero, etc... En una master-class en adalab que di hace tiempo, dediqué una sección que resultó divertida: después de explicar unos pocos conceptos, puse unos ejemplos de "malas gráficas" y las asistentes tenían que buscar los defectos.

Y algunas alternativas:

* O tocar varias librerías con algún ejemplo, diciendo pros y contras, cómo decidir entre ellas, tipo: pandas.plot, seaborn, bokeh, plotly.
* O enfocarnos en una (seaborn seguramente) y dedicarle más tiempo.

Pero depende del formato cómo lo veais vosotras, el tiempo, etc. ya me decís! Si queréis lo hablamos por aquí o email / hangout.

Gracias!!

**Comment by aliciapj** [comment]
Hola!! Perdona por el retraso otra vez, entre el verano y la vuelta, no me he podido poner con esto antes!

Si estás en el grupo de telegram habrás visto que vamos a empezar en breve el nuevo curso y estamos preparando muchas novedades respecto a cursos anteriores: queremos organizar grupos de trabajo para contribuir a proyectos open source, combinado con workshops para integrar a las más junior en cada materia. Hemos creado un google form para coordinar una reunión con chicas que quieran participar activamente en el grupo, así que, si te apetece, molaría que te apuntaras y así te contamos las iniciativas y vemos si te encaja para hacer un workshop de este u otro contenido que te interese. El formulario es este: https://forms.gle/WH41zuZpgAQA7ye68

Muchas gracias otra vez y estamos en contacto!

**Comment by koldLight** [comment]
Hola! Nada, gracias por aceptar la PR. Sí, lo vi en telegram, me acabo de apuntar al form. Tiene muy buena pinta lo que estáis organizando para este año, nos veremos en la reunión!
